### ISSUE TITLE
Dataset issue and accuracy problem

### ISSUE THREAD

**Issue by ClaudeFyre** [soledad921/TEA-GNN#4]
Hi, thanks for your public code!

I got bad accuracy when I train your code on YAGO-WiKi20K, and the only thing I changed is:

parser.add_argument(
    '--data',
    default = 'icews05-15',
    type = str,
    help='choose dataset')

into:

parser.add_argument(
    '--data',
    default = 'YAGO-WIKI20K',
    type = str,
    help='choose dataset')

Is there anything more I need to revise on the code?

**Comment by soledad921** [comment]
> 

you should also change hyperparameters.  Please try to run python main.py --data YAGO-WIKI20K --seed 400 --gamma 3 --dim 100 --lr 0.005

**Comment by soledad921** [comment]
> Hi, thanks for your public code!
> 
> I got bad accuracy when I train your code on YAGO-WiKi20K, and the only thing I changed is:
> 
> parser.add_argument( '--data', default = 'icews05-15', type = str, help='choose dataset')
> 
> into:
> 
> parser.add_argument( '--data', default = 'YAGO-WIKI20K', type = str, help='choose dataset')
> 
> Is there anything more I need to revise on the code?

you should also change hyperparameters. Please try to run python main.py --data YAGO-WIKI20K --seed 400 --gamma 3 --dim 100 --lr 0.005

**Comment by ClaudeFyre** [comment]
> 

Thanks for your reply.
I downloaded your code again this morning and ran it with the command you just provided. Here is the result in the attachment:
[20230112.txt](https://github.com/soledad921/TEA-GNN/files/10397505/20230112.txt)

And I found that here is only YAGO-WIKI50K in data. Could you please provide more about YAGO-WIKI50K-10 and YAGO-WIKI50K-2 you mentioned in your paper?

**Comment by soledad921** [comment]
> > 
> 
> Thanks for your reply. I downloaded your code again this morning and ran it with the command you just provided. Here is the result in the attachment: [20230112.txt](https://github.com/soledad921/TEA-GNN/files/10397505/20230112.txt)
> 
> And I found that here is only YAGO-WIKI50K in data. Could you please provide more about YAGO-WIKI50K-10 and YAGO-WIKI50K-2 you mentioned in your paper?

As seen in the results you provided, after one epoch, the MRR was 0.553, which is the same as the result reported in the Table 4 of my paper.  About YAGO-WIKI50K-10 and YAGO-WIKI50K-2, you only need to change the parameter "seed" in the previous command. YAGO-WIKI50K-10 indicates that the number of seed entity pairs is 50K*10%=5k, so you should input "-seed 5000". You could refer to the table 1 to check the specific seed numbers for different datasets.
